name: my_app
dependencies:
  browser: ">=0.10.0 <0.11.0"
  js: "^0.6.0"
  intl: "^0.12.4"
  slideshow: "^0.1.2"
  polymer: ">=0.15.1 <0.17.0"
  polymer_elements: "^1.0.0-rc.1"
  paper_elements: "^0.7.1+2"
  web_components: "^0.12.0"
  reflectable: "^0.3.3"
  google_maps: "^3.1.0"
transformer:
- polymer
